--- #YAML:1.0
name:               Template-Alloy
version:            1.015
abstract:           TT2/3, HT, HTE, Tmpl, and Velocity Engine
author:
    - Paul Seamons
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::MD5:  1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
