---
abstract: 'TT2/3, HT, HTE, Tmpl, and Velocity Engine'
author:
  - 'Paul Seamons'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.131560'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Alloy
no_index:
  directory:
    - t
    - inc
requires:
  Digest::MD5: 1
version: 1.020
