--- #YAML:1.0
name:                Template-Alloy
version:             1.008
abstract:            TT2/3, HT, HTE, Tmpl, and Velocity Engine
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Digest::MD5:                   1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Paul Seamons
